details:
  name: Freeze prevention check
  description: The outdoor-air damper should be locked out to the minimum position for freeze prevention when the outdoor-air temperature is below 40 F (4 ◦C), and the outdoor-air dampers should be completely closed if the mixed-air temperature becomes lower than 40oF. Given that from the previous check it is possible to automatically extract the minimum OA we can check that in such conditions the damper is at minimum or closed.
  version: 1.0
  author: Roberto Chiosa
  email: roberto.chiosa@polito.it
  created_at: 2024-01-01

