# Config
details:
  name: Check Variables
  description: Checks if a certain AHU has the required variables
  version: 1.0
  author: Roberto Chiosa
  email: roberto.chiosa@polito.it
  created_at: 2024-01-01

analyze_functions:
  - check_variables

