details:
  name: Check Variables
  description: Checks if are there any stuck sensor. The analysis is performed depending on the type of sensor/point.
  version: 1.0
  author: Roberto Chiosa
  email: roberto.chiosa@polito.it
  created_at: 2024-01-01

